# Copyright (c) 2022 Paul Barker <paul@pbarker.dev>
# SPDX-License-Identifier: Apache-2.0

tasks:
  - init: |
        sudo apt install -y python3.8-venv
        pip install invoke build pre-commit
        pre-commit install --install-hooks
        inv build install
    env:
      PRE_COMMIT_HOME: /workspace/.pre-commit
